### ISSUE TITLE
Support URL link in BibTeX misc

### ISSUE THREAD

**Issue by bebatut** [TailorDev/monod#194]
Hi,

It could be nice to support `url` in bibtex entries (link to the cited website).

For example, the following bibtex entry: 

```
@misc{lampa_2015,
  	author = {Lampa, Samuel},
  	title = {A few thoughts on organizing computational (biology) projects},
 	url = {http://bionics.it/posts/organizing-compbio-projects},
    year = {2015},
  	note = {Accessed: 2016-09-01}
}
```

Right now it looks like: "Lampa, S. (2015). A few thoughts on organizing computational (biology) projects. Accessed: 2016-09-01".

It would be better if it'd look: "Lampa, S. (2015). [A few thoughts on organizing computational (biology) projects](http://bionics.it/posts/organizing-compbio-projects). Accessed: 2016-09-01".

Thanks

**Comment by willdurand** [comment]
The code related to this issue is here: https://github.com/TailorDev/monod/blob/master/app/bibtex.js#L174-L180. The `url` attribute is not supported currently, so it should be a matter of adding it like here: https://github.com/TailorDev/monod/blob/master/app/bibtex.js#L151.

The code is tested here: https://github.com/TailorDev/monod/blob/master/app/__tests__/bibtex-test.js, and one could even edit [this fixtures file](https://github.com/TailorDev/monod/blob/master/app/__tests__/fixtures/bib/misc.bib) to see whether the patch is correct.

**Comment by prayashm** [comment]
I want to work on this

**Comment by willdurand** [comment]
Ok @prayashm! 👌

**Comment by prayashm** [comment]
Why didn't this issue get closed? :confused:

**Comment by willdurand** [comment]
ah because I forgot ;-)

**Comment by prayashm** [comment]
I thought it closes automatically when the PR gets merged. :laughing:

**Comment by willdurand** [comment]
It does when you have a commit message containing `fixes #<number>` for instance.
